# Generated by Django 3.1.5 on 2021-01-20 18:35

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bandera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('latitud', models.FloatField(default=43.370682)),
                ('longitud', models.FloatField(default=-8.395913)),
            ],
        ),
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True)),
                ('abreviatura', models.CharField(blank=True, max_length=4, null=True)),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('url_icon', models.URLField(blank=True, default=None, max_length=300, null=True)),
                ('fecha_fundacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True)),
                ('banderas_capturadas', models.IntegerField(default=0, editable=False)),
                ('salt', models.CharField(max_length=16)),
                ('clave_sha_concatenada', models.CharField(max_length=40)),
                ('fundador', models.BooleanField(default=False)),
                ('id_clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetfight.clan')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_caducidad', models.DateTimeField()),
                ('valor_cookie', models.CharField(default='651-t-kMdmMdb32I4JU2pUkkAT0hMR98_xltuDM9R9Sv9FLzrQh4HDYA1g1wiXrsS4WV_SeTZTvE4e9xJ4tmHd4N-Q', max_length=75, unique=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetfight.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='IntentoCaptura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_bandera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetfight.bandera')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetfight.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='bandera',
            name='id_clan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='streetfight.clan'),
        ),
    ]
