# Generated by Django 3.1.5 on 2021-01-19 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True)),
                ('abreviatura', models.CharField(blank=True, max_length=4, null=True)),
                ('color', models.CharField(max_length=7)),
                ('url_icon', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_fundacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True)),
                ('banderas_capturadas', models.IntegerField()),
                ('salt', models.CharField(max_length=40)),
                ('clave_sha_concatenada', models.CharField(max_length=40)),
                ('fundador', models.BooleanField()),
                ('id_clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetfight.clan')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_caducidad', models.DateTimeField()),
                ('valor_cookie', models.CharField(max_length=75, unique=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetfight.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='IntentoCaptura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('id_clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetfight.clan')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetfight.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Bandera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('id_clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='streetfight.clan')),
            ],
        ),
    ]
