# Generated by Django 3.1.5 on 2021-01-20 15:32

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streetfight', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intentocaptura',
            name='id_clan',
        ),
        migrations.AddField(
            model_name='intentocaptura',
            name='id_bandera',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='streetfight.bandera'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bandera',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bandera',
            name='id_clan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='streetfight.clan'),
        ),
        migrations.AlterField(
            model_name='bandera',
            name='latitud',
            field=models.FloatField(default=43.370682),
        ),
        migrations.AlterField(
            model_name='bandera',
            name='longitud',
            field=models.FloatField(default=-8.395913),
        ),
        migrations.AlterField(
            model_name='clan',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='clan',
            name='fecha_fundacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clan',
            name='url_icon',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='intentocaptura',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='valor_cookie',
            field=models.CharField(default='651-NnPKgIl7CUfSmLws0k3WovFXR1-0xt6nX3qwg31uQoNYH_iumSpVDVB_xM3c_K9OXroRy-G9vrhPBXViTy6qxg', max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='banderas_capturadas',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fundador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='salt',
            field=models.CharField(max_length=16),
        ),
    ]
